version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - devopssense_db:/app
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./dashboards/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [api]
  grafana:
    image: grafana/grafana:11.1.4
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./dashboards/grafana/dashboards:/var/lib/grafana/dashboards
      - ./dashboards/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on: [prometheus]
volumes:
  devopssense_db:
